<Project Sdk="Aspire.AppHost.Sdk/13.0.0">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>21e3dfed-f72f-4b90-ad21-e5048269078c</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\XE.DotNetConf2025.ApiService\XE.DotNetConf2025.ApiService.csproj" />
    <ProjectReference Include="..\XE.DotNetConf2025.Web\XE.DotNetConf2025.Web.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Redis" Version="13.1.0" />
    <PackageReference Include="Aspire.Hosting.SqlServer" Version="13.1.0" />
  </ItemGroup>

</Project>
