@ApiService_HostAddress = https://localhost:7558

GET {{ApiService_HostAddress}}/weatherforecast/
Accept: application/json

###


GET {{ApiService_HostAddress}}/speeches
Accept: application/json

###


POST {{ApiService_HostAddress}}/speeches
Content-Type: application/json

{
  "title": "Novità in ASP.NET Core & Blazor",
  "abstract": "In questa sessione vedremo le principali novità che .NET 10 porta per ASP.NET Core e Blazor.",
  "speaker": {
    "name": "Andrea Dottor",
    "email": "andrea.dottor@dev.localhost"
  }
}

###

GET {{ApiService_HostAddress}}/sse-item
Accept: text/event-stream

###